# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: dapr-pubsub
# spec:
#   type: pubsub.redis
#   version: v1
#   metadata:
#   - name: redisHost
#     value: localhost:6379
#   - name: redisPassword
#     value: ""


apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://localhost:5672"
  - name: protocol
    value: amqp  
  - name: hostname
    value: localhost 
  - name: username
    value: user
  - name: password
    value: pass  
  - name: autoAck
    value: false
  - name: enableDeadLetter # Optional enable dead Letter or not
    value: true
  - name: exchangeKind
    value: fanout
