version: '3.4'

services:
  consumerapp:
    image: consumerapp:latest
    build:
      context: .
      dockerfile: Dockerfile

  consumerapp-dapr:
   image: "daprio/daprd:latest"
   container_name: consumerapp-dapr
   command:
      [
        "./daprd",
        "-app-id",
        "consumerapp",
        "-app-port",
        "80",
        "--log-level",
        "debug",
        "--components-path",
        "/components",
      ]
   volumes:
      - ./components:/components